name: hello-world-example
on:
  push:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      -
        name: Do stuff
        run: |
          python3 -m pip install requests
          python3 a.py
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m 'Hey! I add a file for you.' && git push
      -
        name: Say Goodbye
        run: echo "Goodbye!"

